---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  EnvironmentName: 
    Type: String

  VPC:
    Type: String
  
  PublicSubnet1:
    Type: String
  
  PublicSubnet2:
    Type: String

  ALBSecurityGroup:
    Type: String

Resources:
  ApplicationLoadBalancer: # ALB
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-ALB
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets: 
        - Ref: "PublicSubnet1"
        - Ref: "PublicSubnet2"

  LoadBalancerListener: # Port 80
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC

Outputs:
  ApplicationLoadBalancer:
    Description: ALB
    Value: !Ref ApplicationLoadBalancer
    Export:
        Name: !Sub ${AWS::StackName}-ApplicationLoadBalancer

  TargetGroup:
    Description: TG ALB
    Value: !Ref TargetGroup
    Export:
        Name: !Sub ${AWS::StackName}-TargetGroup